# Generated by Django 4.0.1 on 2022-01-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(verbose_name='Company_ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company_name')),
                ('location', models.CharField(max_length=1024, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='Product_ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product_Name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.company')),
            ],
        ),
    ]
